title: GMB South London Universities
email: gmb@arts.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  GMB South London Universities
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: GMBSLU

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

defaults:
    -
     scope:
         path: ""
     values:
         lang: en
         base-url: "/"
    -
     scope:
         path: "*/en"
     values:
         lang: en
         base-url: "/"
    -
     scope:
         path: "*/es"
     values:
         lang: es
         base-url: "/es/"


collections:
  campaigns:
     output: true
  pages:
     output: true
  news:
     output: true

